; Listing generated by Microsoft (R) Optimizing Compiler Version 19.42.34435.0 

	TITLE	C:\Users\rpg26\OneDrive\Desktop\Source\VS2010\Buckland_Chapter7 to 10_Raven\Debug\Goal_SayPhrase.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
